### ISSUE TITLE
NameError: name 'type_' is not defined on line 135 

### ISSUE THREAD

**Issue by cclauss** [NiklasRosenstein/pydoc-markdown#12]
```
File "./pydoc_markdown/__init__.py", line 135, in write_class_member
    prefix = type_.__name__
NameError: name 'type_' is not defined
```

I believe this is supposed to be tpe instead of type_.

**Comment by NiklasRosenstein** [comment]
That is correct, however you are using a pretty old version of pydoc-markdown. The v2 is quite a lot different and uses MkDocs. There's [v2.0.0.dev0](https://pypi.python.org/pypi/pydoc-markdown/2.0.0.dev0) in PyPI, to install it you need to specify the version number explicitly on the command-line.

    pip install --upgrade pydoc-markdown==2.0.0.dev0

Check out https://niklasrosenstein.github.io/pydoc-markdown/

**Comment by cclauss** [comment]
Ouch!  The original version had a bug but once I fixed that, I could get it to read in a Python file and write out a .md file with no fuss, no muss.  I can not make heads or tails out of v2!  It seems to pip install at least 10 modules and then gives me something that can not read in a Python file and write our a .md file.  I do not need a web server, a static site generator, etc.  I just want to convert a Python file into a .md file.  Can you please correct my step-by-step instructions below for getting to a .md file?  Thanks.

```
$ mkdir pydoc-markdown
$ python3 -m venv pydoc-markdown
$ cd pydoc-markdown
$ . bin/activate
$ pip install --upgrade pydoc-markdown==2.0.0.dev0
$ cp ~/python/my_cool_script.py ./bin
$ pydocmd  my_cool_script  # this part was so simple in v1
```

**Comment by NiklasRosenstein** [comment]
Sorry for the troubles. I've had some more complex requirements that
required a more complex solution. As it is at the moment, it wraps around
the MkDocs command line interface amd generates the Markdown files before
they are converted to HTML MkDocs.

I do agree with you that the old way was convenient for small (single file)
Python modules. I'll add something tomorrow and keep you posted.


On 26 Feb 2017 21:31, "cclauss" <notifications@github.com> wrote:

Ouch! The original version had a bug but once I fixed that, I could get it
to read in a Python file and write out a .md file with no fuss, no muss. I
can not make heads or tails out of v2! It seems to pip install at least 10
modules and then gives me something that can not read in a Python file and
write our a .md file. I do not need a web server, a static site generator,
etc. I just want to convert a Python file into a .md file. Can you please
correct my step-by-step instructions below for getting to a .md file?
Thanks.

$ mkdir pydoc-markdown
$ python3 -m venv pydoc-markdown
$ cd pydoc-markdown
$ . bin/activate
$ pip install --upgrade pydoc-markdown==2.0.0.dev0
$ cp ~/python/my_cool_script.py ./bin
$ pydocmd  my_cool_script  # this part was so simple in v1

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/NiklasRosenstein/pydoc-markdown/issues/12#issuecomment-282584926>,
or mute the thread

**Comment by cclauss** [comment]
Understood.  Thanks much.

**Comment by NiklasRosenstein** [comment]
I just added a `pydocmd simple` command. https://github.com/NiklasRosenstein/pydoc-markdown/commit/1e1f6ffa1beab568d5fea301adc02564a98181e5

There's a description of the command in [README.md](https://github.com/NiklasRosenstein/pydoc-markdown/blob/1e1f6ffa1beab568d5fea301adc02564a98181e5/README.md). From your example above, you can use it like

    pydocmd simple my_cool_script > docs.md
