### ISSUE TITLE
extras not handled properly?

### ISSUE THREAD

**Issue by odoublewen** [NiklasRosenstein/pydoc-markdown#256]
**Environment**

- Pydoc-Markdown Version: v4.6.3
- Python Version: v3.8.6
- Operating System: macos

**Describe the bug**

The extras do not get installed, when I use pip or pipx to install pydoc-markdown.  I've tried both:

`pip install pydoc-markdown[novella]`
and
`pipx install pydoc-markdown[novella]`

Both commands complete without error, but without installing package `novella`.  Perhaps this is a bug with the poetry packaging of this project?

I've confirmed that I can install "extras" from other packages, e.g., `pip install "dask[dataframe]"` gives me the expected extras.

**Expected behavior**

I expect novella to be installed, as specified here:
https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pyproject.toml#L51

**Comment by NiklasRosenstein** [comment]
Hey! Thanks for raising this issue. You're right, this doesn't quite work. The extra is installed by Pipx, but it doesn't recognize the "novella" script as one that should be linked into your PATH because it comes from a dependency. I should update the documentation here.

 To use it with Pipx, you either need to pass the `--include-deps` flag (thought this also adds commands from other dependencies, such as `docspec`, `docspec-python`, `normalizer`, `watchmedo`, `yapf` and `yapf-diff`), or install `novella` with Pipx instead and inject Pydoc-Markdown.

    $ pipx install novella
    $ pipx inject novella pydoc-markdown

Let me know how this works for you and I'll fix the docs!

Cheers,

**Comment by odoublewen** [comment]
Yes, your suggestion did solve this problem.  Thanks.
